// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2oL1PwvGkjno8cxuTd8F-75DXNOnilTc',
    appId: '1:303237136039:web:e0dcc61a5c95a69680a582',
    messagingSenderId: '303237136039',
    projectId: 'flutter-app-54054',
    authDomain: 'flutter-app-54054.firebaseapp.com',
    databaseURL: 'https://flutter-app-54054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-54054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtszXFciwJFuF6rQpax252VDf5ru7ZeM',
    appId: '1:303237136039:android:9c2d914035c7c57d80a582',
    messagingSenderId: '303237136039',
    projectId: 'flutter-app-54054',
    databaseURL: 'https://flutter-app-54054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-54054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA36yqF4hjjth1G9ocELKzZaGWHXH-VgdE',
    appId: '1:303237136039:ios:05237b0e4ba44a2e80a582',
    messagingSenderId: '303237136039',
    projectId: 'flutter-app-54054',
    databaseURL: 'https://flutter-app-54054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-54054.appspot.com',
    iosBundleId: 'com.example.applicationFurnitureMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA36yqF4hjjth1G9ocELKzZaGWHXH-VgdE',
    appId: '1:303237136039:ios:05237b0e4ba44a2e80a582',
    messagingSenderId: '303237136039',
    projectId: 'flutter-app-54054',
    databaseURL: 'https://flutter-app-54054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-54054.appspot.com',
    iosBundleId: 'com.example.applicationFurnitureMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2oL1PwvGkjno8cxuTd8F-75DXNOnilTc',
    appId: '1:303237136039:web:f62a12a41eedd7fa80a582',
    messagingSenderId: '303237136039',
    projectId: 'flutter-app-54054',
    authDomain: 'flutter-app-54054.firebaseapp.com',
    databaseURL: 'https://flutter-app-54054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-54054.appspot.com',
  );
}
